### PR TITLE
Upgrade to ember-cli 0.2.3

### PR DESCRIPTION
**Pull request by knownasilya**
Although for some reason it doesn't trigger the custom events..

### CODE REVIEW

**Comment by pixelhandler** [comment]
Looks like there is a build issue "Path or pattern "vendor/ember-off-canvas-components.css" did not match any files" will need to look into that.

Thanks for the updates :)

**Comment by knownasilya** [comment]
@pixelhandler `npm run sass` solves that issue.

**Comment by pixelhandler** [comment]
@knownasilya yeah I used to have the sass step in a post install but moved it to a prepublish setup. Most who install to consume have no need to build the css. I update the Readme and Travis files with the `npm run sass` in a new commit off your branch. 

Perhaps add me as a contributor on your fork https://github.com/knownasilya/ember-off-canvas-components or merge in https://github.com/knownasilya/ember-off-canvas-components/pull/1

**Comment by pixelhandler** [comment]
With the changes on my branch travis passes, https://travis-ci.org/pixelhandler/ember-off-canvas-components/builds/61832125

**Comment by pixelhandler** [comment]
@knownasilya seems that something has changed with when customEvents can be defined.

To work around I added to the (dummy) application… [test/dummy/app/app.js]
```javascript
Ember.MODEL_FACTORY_INJECTIONS = true;

Ember.String.w('toggle expand collapse').forEach(function (prefix) {
  var name = Ember.String.fmt("%@OffCanvas", prefix);
  customEvents[name] = name;
});

App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver: Resolver,
  customEvents: customEvents
});

loadInitializers(App, config.modulePrefix);
```

Previously the initializer was able to register the custom events like so… https://github.com/pixelhandler/ember-off-canvas-components/blob/master/addon/initializers/custom-events.js#L3-L10

tl:dr - In the past I’ve been able to add customEvents to an application inside an initializer, but now that doesn’t work. I have to setup the customEvents using Application.extend or Application.create - what happened?

**Comment by knownasilya** [comment]
Sounds like it might be related to the fastboot work, and the two types of initializers.

**Comment by pixelhandler** [comment]
I may need to convert the customEvents to actions, I don't really like that as the template use will need to wire the target component for the actions.

**Comment by pixelhandler** [comment]
I'll merge this in, thanks. Will need to fix the customEvents / or switch to actions separately.

**Comment by pixelhandler** [comment]
@knownasilya @runspired I'll need to stick with using custom events as I have support for outlets inside the on/off canvas templates not sure if there will ever be support for passing current context/targetObject into an outlet, ever (by design outlets have their own context, not that of the parent component). See https://github.com/pixelhandler/ember-off-canvas-components/compare/silly-components-cant-send-content-into-outlets-use-custom-events-then an attempt to use actions which fails with the use of outlets in the on/off canvas components.

For now I'll add more instruction / ceremony (version bump) that explains the need to setup the custom events in the consuming application. Or, will need to pack some data attributes in to a standard event for inspecting in the eoc-viewport.

**Pull request merged**
